server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: app
    password: app
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
      encoding: UTF-8
logging:
  level:
    root: info
    com.example: info
    businessLog: info
  file:
    name: logs/demo.log
